// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.RecycleRushSuperStructure.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc692.RecycleRushSuperStructure.Robot;

/**
 *
 */
public class  elevatorGoToGroundLevel extends Command {

    public elevatorGoToGroundLevel() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if(Robot.elevator.onStepLevel())
    	{
    		Robot.elevator.elevatorDown();
    		Robot.elevator.setElevatorMovingDown();
    		//sets elevator as moving down (-1)
    		//AC 1/19/15
    		System.out.println("Elevator on step level!");
    		System.out.println("Going down to ground!");
    	}
    	else if(Robot.elevator.onTopLoadLevel())
    	{
    		Robot.elevator.elevatorDown();
    		Robot.elevator.setElevatorMovingDown();
    		//sets elevator as moving down
    		//AC 1/19/15
    		System.out.println("Elevator on top level!");
    		System.out.println("Going down to ground!");
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        if(Robot.elevator.onGroundFloor())
        {
        	Robot.elevator.setDonePosition();
        	System.out.println("Elevator on ground floor!");
        	System.out.println("Elevator stopping!");
        	return true;
        }
        else
        {
        	return false;
        }
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.elevator.elevatorStop();
    	System.out.println("Elevator has reached the end method!");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	if(Robot.elevator.isMovingDown() && !Robot.elevator.onGroundFloor())
    		//if robot is set to moving down and not on ground floor
    		// ! = not
    	{
    		Robot.elevator.elevatorDown();
    		System.out.println("Going down to ground!");
    	}
    	end();
    	//if elevator is moving down, keep going down until hits the ground level
    	//calls end method to stop
    	//AC 1/19/15
    }
    /*
     * if elevator is on top or step level the elevator will go down 
     * NEEDS AN INTERRUPT!
     * AC 1/16/15
     */
}
