// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.RecycleRushSuperStructure.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc692.RecycleRushSuperStructure.Robot;

/**
 *
 */
public class  elevatorGoToStepLevel extends Command {

    public elevatorGoToStepLevel() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if(Robot.elevator.onGroundFloor())
    	{
    		Robot.elevator.elevatorUp();
    		Robot.elevator.setElevatorMovingUp();
    		//sets elevator is moving up
    		//AC 1/19/15
    		System.out.println("Elevator on ground floor!");
    		System.out.println("Going up to step level!");
    	}
    	else if(Robot.elevator.onTopLoadLevel())
    	{
    		Robot.elevator.elevatorDown();
    		Robot.elevator.setElevatorMovingDown();
    		//elevator is moving down
    		//AC 1/19/15
    		System.out.println("Elevator on top floor!");
    		System.out.println("Going down to step level!");
    	}
    	/*
    	 * Do we need another conditional (like a final "else" statement) here? 
    	 * AC 1/16/15
    	 */
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        if(Robot.elevator.onStepLevel())
        {
        	Robot.elevator.setDonePosition();
        	System.out.println("Elevator on step floor!");
        	System.out.println("Elevator stopping!");
        	return true;
        }
        else
        {
        	return false;
        }
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.elevator.elevatorStop();
    	System.out.println("Elevator has reached end method!");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	if(Robot.elevator.isMovingDown() && !Robot.elevator.onStepLevel())
    		//if robot is moving down and not on step level
    	{
    		Robot.elevator.elevatorDown();
    		System.out.println("Going down to step level!");
    	}
    	else if(Robot.elevator.isMovingUp() && !Robot.elevator.onStepLevel())
    	{
    		Robot.elevator.elevatorUp();
    		System.out.println("Going up to step level!");
    	}
    	end();
    	//if elevator is moving up when interrupted keep moving up until at step
    	//if elevator is moving down when interrupted keep moving down until at step
    	//AC 1/19/15
    }
    //if elevator is on top level when called, platform will go down
    //if elevator is on bottom level when called, platform will go up
    //need to make an interrupt method!
    //AC 1/16/15
    
    /*
     * WHAT WE WANT THE (STEP)ELEVATOR TO DO:
     * -If platform is on ground level, go up to step 
     * -If platform is on top load level, go down to step
     * --Interrupt code (need to check on what do do though) 
     * --stop and go automatically to correct floor?
     * --keep going to floor and stop?
     * --stop? 
     * --?? ? 
     * AC 1/16/15
     */
}
