// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.RecycleRushSuperStructure.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc692.RecycleRushSuperStructure.Robot;

/**
 *
 */
public class  elevatorGoToTopLevel extends Command {

    public elevatorGoToTopLevel() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if(Robot.elevator.onStepLevel())
    	{
    		Robot.elevator.elevatorUp();
    		Robot.elevator.setElevatorMovingUp();
    		System.out.println("Elevator on step level!");
    		System.out.println("Going up to top level!");
    	}
    	else if(Robot.elevator.onGroundFloor())
    	{
    		Robot.elevator.elevatorUp();
    		Robot.elevator.setElevatorMovingUp();
    		System.out.println("Elevator on ground floor!");
    		System.out.println("Going up to top level!");
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        if(Robot.elevator.onTopLoadLevel())
        {
        	Robot.elevator.setDonePosition();
        	System.out.println("Elevator on top floor!");
        	System.out.println("Stopping!");
        	return true;
        }
        else
        {
        	return false;
        }
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.elevator.elevatorStop();
    	System.out.println("Elevator has reached end method!");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	if(Robot.elevator.isMovingUp() && !Robot.elevator.onTopLoadLevel())
    	{
    		Robot.elevator.elevatorUp();
    		System.out.println("Going up to top level!");
    	}
    	end();
    }
    /*
     * If elevator is on ground or step it goes up
     * AC 1/16/15
     */
}
