// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.RecycleRushSuperStructure.subsystems;

import org.usfirst.frc692.RecycleRushSuperStructure.RobotMap;
import org.usfirst.frc692.RecycleRushSuperStructure.commands.*;
import edu.wpi.first.wpilibj.SpeedController;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class ToteAlignment extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController rotatingAlignmentMotor = RobotMap.toteAlignmentrotatingAlignmentMotor;
    DigitalInput rightTopAlignmentSensor = RobotMap.toteAlignmentrightTopAlignmentSensor;
    DigitalInput rightMiddleAlignmentSensor = RobotMap.toteAlignmentrightMiddleAlignmentSensor;
    DigitalInput leftMiddleAlignmentSensor = RobotMap.toteAlignmentleftMiddleAlignmentSensor;
    DigitalInput leftBottomAlignmentSensor = RobotMap.toteAlignmentleftBottomAlignmentSensor;
    DigitalInput suctionCupAlignmentSensor = RobotMap.toteAlignmentsuctionCupAlignmentSensor;
    DigitalInput leftTopAlignmentSensor = RobotMap.toteAlignmentleftTopAlignmentSensor;
    DigitalInput rightBottomAlignmentSensor = RobotMap.toteAlignmentrightBottomAlignmentSensor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

